version: "3"
services: 
  node-app-arni:
    build: . # passing the path of dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - PORT=3000
#    env_file:
#     - ./.env